modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="czasclient"
version="1.0.0"
displayName="Czas Client"
credits="348 s"
authors="348 s"
description="A comprehensive Minecraft client by 348 s"

[[dependencies.czasclient]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.czasclient]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.21.4]"
ordering="NONE"
side="BOTH"
